"""
Install pyenv, pyenv-virtualenv, and pyenv-doctor on a remote server via SSH.
And set PYTHON_BUILD_MIRROR_URL to Tsinghua Tuna mirror.
"""

import subprocess
import os
import shutil

from log import Log

ADD_REMOTE_PATH_PYSCRIPT = """
import os

CODE = \"\"\"
### python environment management - pyenv
### autogenerated by tools-installer (please do not delete this line)
export PYENV_ROOT="{pyenv_root}"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
export PYTHON_BUILD_MIRROR_URL="https://mirrors.tuna.tsinghua.edu.cn/python"
export PYTHON_BUILD_MIRROR_URL_SKIP_CHECKSUM=1
\"\"\"


def main():
    # get the user's shell profile
    bashrc = os.path.expanduser("~/.bashrc")
    bashrc_contents = ""
    if os.path.exists(bashrc):
        with open(bashrc, "r") as f:
            bashrc_contents = f.read()
    # check if pyenv lines are already present
    if "### python environment management - pyenv" in bashrc_contents:
        print("[running in remote server] pyenv configuration already exists in .bashrc")
        return
    # append pyenv configuration
    with open(bashrc, "a") as f:
        f.write("\\n" + CODE + "\\n")
    print("[running in remote server] pyenv configuration added to .bashrc")

if __name__ == "__main__":
    main()
"""


class PyenvInstaller:
    def __init__(
        self,
        /,
        remote_server_ssh_key: str,
        remote_server_user: str,
        remote_server_host: str,
        remote_server_dist_path: str = "~/.pyenv",
        git_base_url: str = "https://github.com",
    ):
        if git_base_url.endswith("/"):
            git_base_url = git_base_url[:-1]
        self.git_base_url = git_base_url

        # https://github.com/pyenv/pyenv
        self.pyenv_git_url = f"{self.git_base_url}/pyenv/pyenv.git"
        self.pyenv_doctor_git_url = f"{self.git_base_url}/pyenv/pyenv-doctor.git"
        self.pyenv_virtualenv_git_url = (
            f"{self.git_base_url}/pyenv/pyenv-virtualenv.git"
        )
        self.cache_dir = ".cache/pyenv"
        self.version = "master"

        self.remote_server_ssh_key = remote_server_ssh_key
        self.remote_server_user = remote_server_user
        self.remote_server_host = remote_server_host
        self.remote_server_dist_path = remote_server_dist_path

    def _make_cache_dir(self):
        """
        Create cache dir CWD/.cache/pyenv for saving downloaded files.
        """
        Log.info("Creating cache directory for pyenv...")
        if os.path.exists(self.cache_dir):
            shutil.rmtree(self.cache_dir)
        os.makedirs(self.cache_dir, exist_ok=True)
        Log.info(f"Created cache directory at {self.cache_dir}")

    def _clone_repo(self, repo_url: str, dest_dir: str):
        Log.info(f"Cloning {repo_url} into {dest_dir}...")
        subprocess.run(
            [
                "git",
                "clone",
                "--branch",
                self.version,
                "--depth",
                "1",
                repo_url,
                dest_dir,
            ],
            check=True,
        )
        Log.info(f"Cloned {repo_url} into {dest_dir}")

    def _download(self):
        self._clone_repo(self.pyenv_git_url, os.path.join(self.cache_dir, "pyenv"))

        self._clone_repo(
            self.pyenv_doctor_git_url,
            os.path.join(self.cache_dir, "pyenv", "plugins", "pyenv-doctor"),
        )

        self._clone_repo(
            self.pyenv_virtualenv_git_url,
            os.path.join(self.cache_dir, "pyenv", "plugins", "pyenv-virtualenv"),
        )

    def _gzip_cache(self):
        Log.info("Compressing downloaded pyenv...")
        tarball_path = os.path.join(self.cache_dir, "pyenv.tar.gz")

        if os.path.exists(tarball_path):
            os.remove(tarball_path)

        subprocess.run(
            [
                "tar",
                "-czf",
                tarball_path,
                "-C",
                os.path.join(self.cache_dir, "pyenv"),
                ".",
            ],
            check=True,
        )
        Log.info(f"Compressed pyenv to {tarball_path}")
        return tarball_path

    def _get_remote_gzip_path(self):
        return "~/tools-installer/pyenv.tar.gz"

    def _makesure_remote_dir(self):
        Log.info("Ensuring remote directory exists...")
        subprocess.run(
            [
                "ssh",
                "-i",
                self.remote_server_ssh_key,
                f"{self.remote_server_user}@{self.remote_server_host}",
                "mkdir -p ~/tools-installer",
            ],
            check=True,
        )
        Log.info("Remote directory ensured.")

    def _upload_to_remote(self):
        Log.info("Uploading pyenv.tar.gz to remote server...")
        gzip_path = self._gzip_cache()
        remote_gzip_path = self._get_remote_gzip_path()

        subprocess.run(
            [
                "scp",
                "-i",
                self.remote_server_ssh_key,
                "-r",
                gzip_path,
                f"{self.remote_server_user}@{self.remote_server_host}:{remote_gzip_path}",
            ],
            check=True,
        )
        Log.info("Uploaded pyenv.tar.gz to remote server.")

    def _unpack_on_remote(self):
        Log.info("Unpacking pyenv on remote server...")
        remote_gzip_path = self._get_remote_gzip_path()
        subprocess.run(
            [
                "ssh",
                "-i",
                self.remote_server_ssh_key,
                f"{self.remote_server_user}@{self.remote_server_host}",
                f"mkdir -p {self.remote_server_dist_path} && tar -xzf {remote_gzip_path} -C {self.remote_server_dist_path}",
            ],
            check=True,
        )
        Log.info("Unpacked pyenv on remote server.")

    def _add_remote_path(self):
        Log.info("Adding pyenv to remote server PATH...")
        formated_script = ADD_REMOTE_PATH_PYSCRIPT.format(
            pyenv_root=self.remote_server_dist_path
        )

        # save script to local temp file
        temp_script_path = os.path.join(self.cache_dir, "add_pyenv_path.py")
        with open(temp_script_path, "w") as f:
            f.write(formated_script)

        # upload script to remote server
        remote_script_path = "~/tools-installer/add_pyenv_path.py"
        subprocess.run(
            [
                "scp",
                "-i",
                self.remote_server_ssh_key,
                temp_script_path,
                f"{self.remote_server_user}@{self.remote_server_host}:{remote_script_path}",
            ],
            check=True,
        )

        # execute script on remote server
        subprocess.run(
            [
                "ssh",
                "-i",
                self.remote_server_ssh_key,
                f"{self.remote_server_user}@{self.remote_server_host}",
                f"python3 {remote_script_path}",
            ],
            check=True,
        )

    def _build_dependencies(self):
        need_deps = [
            "make",
            "build-essential",
            "libssl-dev",
            "zlib1g-dev",
            "libreadline-dev",
            "libsqlite3-dev",
            "curl",
            "git",
            "libncursesw5-dev",
            "xz-utils",
            "tk-dev",
            "libxml2-dev",
            "libxmlsec1-dev",
            "libffi-dev",
            "liblzma-dev",
        ]
        return need_deps

    def install(self):
        self._make_cache_dir()
        self._download()
        self._makesure_remote_dir()
        self._upload_to_remote()
        self._unpack_on_remote()
        self._add_remote_path()
        Log.info("pyenv installation completed.")
        Log.info(
            "You may need to install the following dependencies on the remote server to build Python:"
        )
        Log.info(f"apt install {' '.join(self._build_dependencies())}")
